openapi: 3.0.0
info:
  version: 1.0.0
  title: Cadence13 Dashboard API

paths:
  /networks:
    get:
      summary: List all authorized networks
      operationId: cadence13.api.showtime.network.get_networks
      tags:
        - networks
      responses:
        200:
          description: An array of networks
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Network'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new network
      operationId: cadence13.api.showtime.network.create_network
      tags:
        - networks
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /networks/{networkGuid}/podcasts:
    get:
      summary: List all podcasts in a network
      operationId: cadence13.api.showtime.network.get_podcasts
      tags:
        - networks
        - podcasts
      parameters:
        - name: networkGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /podcasts:
    get:
      summary: List all authorized podcasts
      operationId: cadence13.api.showtime.podcast.get_podcasts
      tags:
        - podcasts
      parameters:
        - name: startAfter
          in: query
          schema:
            $ref: '#/components/schemas/UUID'
        - name: endingBefore
          in: query
          schema:
            $ref: '#/components/schemas/UUID'
        - name: limit
          in: query
          schema:
            type: integer
      responses:
        200:
          description: A paged array of pets
          content:
            application/json:
              schema:
                type: object
                required:
                  - results
                  - links
                properties:
                  links:
                    type: object
                    properties:
                      next:
                        type: string
                        example: '/podcasts?startAfter=49cf2579-0167-46f8-a1ff-4912f2b8bbbc'
                      prev:
                        type: string
                        example: '/podcasts?endingBefore=acf6611b-6c4f-4c4f-b6d0-40a38c8abdb9'
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Podcast'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /podcasts/{podcastGuid}:
    get:
      summary: Gets a podcast
      operationId: cadence13.api.showtime.podcast.get_podcast
      tags:
        - podcasts
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: Detailed information for a podcast
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Podcast'

        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      summary: Update an existing podcast
      operationId: cadence13.api.showtime.podcast.update_podcast
      tags:
        - podcasts
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /podcasts/{podcastGuid}/episodes:
    get:
      summary: List all episodes in a podcast
      operationId: cadence13.api.showtime.podcast.get_episodes
      tags:
        - podcasts
        - episodes
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: A paged array of episodes
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Episode'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /podcasts/{podcastGuid}/subscription-urls:
    get:
      operationId: cadence13.api.showtime.podcast.get_subscription_urls
      tags:
        - podcasts
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: Array of podcast subscriptions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionUrls'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      operationId: cadence13.api.showtime.podcast.patch_subscription_urls
      tags:
        - podcasts
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubscriptionUrls'
      responses:
        200:
          description: Update successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscriptionUrls'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /podcasts/{podcastGuid}/social-media-urls:
    get:
      operationId: cadence13.api.showtime.podcast.get_social_media_urls
      tags:
        - podcasts
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: Social media URLs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialMediaUrls'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    patch:
      operationId: cadence13.api.showtime.podcast.patch_social_media_urls
      tags:
        - podcasts
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SocialMediaUrls'
      responses:
        200:
          description: Social media URLs
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SocialMediaUrls'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /podcasts/{podcastGuid}/crew-members:
    get:
      summary: Get a list of crew members associated with the podcast
      operationId: cadence13.api.showtime.podcast.get_crew_members
      tags:
        - podcasts
        - crew
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: An array of crew members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CrewMember'

    post:
      operationId: cadence13.api.showtime.crew.create_crew_member
      tags:
        - podcasts
        - crew
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /podcasts/{podcastGuid}/image-upload-url:
    post:
      summary: Generate a pre-signed URL to where an image will be uploaded
      operationId: cadence13.api.showtime.podcast.create_image_upload_url
      tags:
        - podcasts
      parameters:
        - name: podcastGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: The presigned POST URL and S3 access credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PresignedS3PostUrl'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /episodes/{episodeGuid}:
    patch:
      summary: Update an existing episode
      operationId: cadence13.api.showtime.episode.update_episode
      tags:
        - episodes
      parameters:
        - name: episodeGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /crew-members/{crewMemberGuid}:
    get:
      summary: Get crew member details
      operationId: cadence13.api.showtime.crew.get_crew_member
      tags:
        - crew
      parameters:
        - name: crewMemberGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: Return a single crew member
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrewMember'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    patch:
      summary: Update crew member details
      operationId: cadence13.api.showtime.crew.patch_crew_member
      tags:
        - crew
      parameters:
        - name: crewMemberGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete crew member
      operationId: cadence13.api.showtime.crew.delete_crew_member
      tags:
        - crew
      parameters:
        - name: crewMemberGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /crew-members/{crewMemberGuid}/image-upload-url:
    post:
      summary: Generate a pre-signed URL to where an image will be uploaded
      operationId: cadence13.api.showtime.crew.create_image_upload_url
      tags:
        - crew
      parameters:
        - name: crewMemberGuid
          in: path
          required: true
          schema:
            $ref: '#/components/schemas/UUID'
      responses:
        200:
          description: The presigned POST URL and S3 access credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PresignedS3PostUrl'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


components:
  schemas:
    UUID:
      type: string
      pattern: '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'

    PresignedS3PostUrl:
      properties:
        url:
          type: string
        fields:
          type: object

    ImageUrls:
      properties:
        original:
          type: string
        600px:
          type: string

    Network:
      required:
        - guid
        - name
      properties:
        guid:
          $ref: '#/components/schemas/UUID'
        name:
          type: string

    SubscriptionUrls:
      properties:
        applePodcasts:
          type: string
          nullable: true
        googlePlay:
          type: string
          nullable: true
        googlePodcasts:
          type: string
          nullable: true
        stitcher:
          type: string
          nullable: true
        spotify:
          type: string
          nullable: true
        radioCom:
          type: string
          nullable: true
        iHeart:
          type: string
          nullable: true
        locked:
          type: array
          items:
            type: string
            enum:
              - applePodcasts
              - googlePlay
              - googlePodcasts
              - stitcher
              - spotify
              - radioCom
              - iHeart

    SocialMediaUrls:
      properties:
        facebook:
          type: string
          nullable: true
        pinterest:
          type: string
          nullable: true
        instagram:
          type: string
          nullable: true
        twitter:
          type: string
          nullable: true
        reddit:
          type: string
          nullable: true
        locked:
          type: array
          items:
            type: string
            enum:
              - facebook
              - pinterest
              - instagram
              - twitter
              - reddit

    CrewRole:
      type: string
      enum:
        - HOST
        - CO_HOST

    CrewMember:
      properties:
        guid:
          $ref: '#/components/schemas/UUID'
        role:
          $ref: '#/components/schemas/CrewRole'
        firstName:
          type: string
        middleName:
          type: string
          nullable: true
        lastName:
          type: string
        biography:
          type: string
        imageUrls:
          $ref: '#/components/schemas/ImageUrls'

    PodcastBase:
      properties:
        guid:
          $ref: '#/components/schemas/UUID'
        slug:
          type: string
        title:
          type: string
        imageUrls:
          $ref: '#/components/schemas/ImageUrls'
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
        tags:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            type: string

    Podcast:
      properties:
        guid:
          $ref: '#/components/schemas/UUID'
        slug:
          type: string
          nullable: true
        title:
          type: string
          nullable: true
        subtitle:
          type: string
          nullable: true
        summary:
          type: string
          nullable: true
        copyright:
          type: string
          nullable: true
        author:
          type: string
          nullable: true
        websiteUrl:
          type: string
          nullable: true
        feedUrl:
          type: string
        imageUrls:
          $ref: '#/components/schemas/ImageUrls'
        ownerName:
          type: string
          nullable: true
        ownerEmail:
          type: string
          nullable: true
        podcastType:
          type: string
          enum:
            - EPISODIC
            - SERIAL
        isExplicit:
          type: boolean
          nullable: true
        status:
          type: string
          enum:
            - ACTIVE
            - INACTIVE
        subscriptionUrls:
          $ref: '#/components/schemas/SubscriptionUrls'
        socialMediaUrls:
          $ref: '#/components/schemas/SocialMediaUrls'
        crew:
          type: array
          items:
            $ref: '#/components/schemas/CrewMember'
        tags:
          type: array
          items:
            type: string
        categories:
          type: array
          items:
            type: string
        locked:
          type: array
          items:
            type: string
            enum:
              - slug
              - title
              - subtitle
              - summary
              - image

    Episode:
      required:
        - guid
      properties:
        guid:
          $ref: "#/components/schemas/UUID"
        season_no:
          type: integer
          format: int32
        episode_no:
          type: integer
          format: int32
        title:
          type: string
        subtitle:
          type: string
        summary:
          type: string
        author:
          type: string
        episode_type:
          type: string
        image_url:
          type: string
        audio_url:
          type: string
        is_explicit:
          type: boolean
        published_at:
          type: string
          format: date-time
        status:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string